# serializer :
# 1.> validate incoming API data
# 2.> converts data into clean python format


from rest_framework import serializers


class ProductSerializer(serializers.Serializer):
    # id is generated by store therefore read only therefore user should not send ID
    id = serializers.IntegerField(read_only=True)
    name = serializers.CharField(max_length=200)
    description = serializers.CharField()
    category = serializers.CharField(max_length=100)
    price = serializers.DecimalField(max_digits=10, decimal_places=2)
    # brand is optional even if client sends {brand = ""} then also it will work
    brand = serializers.CharField(
        max_length=100, required=False, allow_blank=True)
    quantity = serializers.IntegerField()

    # custom validations

    # {name = {  }} should be rejected
    def validate_name(self, value):
        if not value.strip():
            raise serializers.ValidationError("Name cannot be empty")
        return value

    def validate_category(self, value):
        if not value.strip():
            raise serializers.ValidationError("Category cannot be empty.")
        return value

    def validate_price(self, value):
        if value <= 0:
            raise serializers.ValidationError("Price must be greater than 0.")
        return value

    def validate_quantity(self, value):
        if value < 0:
            raise serializers.ValidationError("Quantity cannot be negative.")
        return value

    def validate_brand(self, value):
        if value != "" and not value.strip():
            raise serializers.ValidationError("Brand cannot be only spaces.")
        return value
